version: 0.2
 
phases:
  build:
    commands:
      - ./gradlew clean build -x test
  post_build:
    commands:
      - ls -l
      - ls -l build
      - ls -l build/libs
artifacts:
  files:
    - 'build/libs/awscodedeploy-null.null.jar'